---
title: "A Collection of Python Examples"
author: "Fan Wang"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Python Implementation Examples for Research Tasks"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    pandoc_args: '_output_kniti_pdf.yaml'
    includes:
      in_header: 'preamble_book.tex'
  html_document:
    pandoc_args: '_output_kniti_html.yaml'
always_allow_html: true
github-repo: fanwangecon/R4Econ
---

```{r global_options, include = FALSE}
source(".Rprofile")
```

# Preface {-}

`r text_top_count`

The work-in-progress [pyfan](https://github.com/FanWangEcon/pyfan) repository contains:

1. Tutorials and examples for various research tasks: [**bookdown site**](https://fanwangecon.github.io/pyfan/bookdown) and [**bookdown pdf**](https://fanwangecon.github.io/pyfan/bookdown/A-Collection-of-Python-Examples.pdf).
2. A package for basic data, graph and research tasks: [**readthedocs**](https://pyfan.readthedocs.io/en/latest/) and [**pypi**](https://pypi.org/project/pyfan/).

Materials are gathered from various [projects](https://fanwangecon.github.io/research) in which python code is used for research and paper-administrative tasks. Files are from [**Fan**](https://fanwangecon.github.io/)'s [pyfan](https://github.com/FanWangEcon/pyfan) repository which has an associated [package](https://pypi.org/project/pyfan/). The package functionalize various tasks tested out in the Rmd files. In addition, the [pyecon](https://github.com/FanWangEcon/pyecon) repository and the associated [package](https://pypi.org/project/pyecon/) ([readthedocs](https://pyfan.readthedocs.io/en/latest/autoapi/pyfan/index.html#module-pyfan)) contain functions and rmd files related explicitly to solving economic models.

From [Fan](https://fanwangecon.github.io/)'s other repositories: For dynamic borrowing and savings problems, see [Dynamic Asset Repository (Matlab)](https://fanwangecon.github.io/CodeDynaAsset/); For code examples, see also [Matlab Example Code](https://fanwangecon.github.io/M4Econ/),  [R Example Code](https://fanwangecon.github.io/R4Econ/), and [Stata Example Code](https://fanwangecon.github.io/Stata4Econ/); For intro econ with Matlab, see [Intro Mathematics for Economists](https://fanwangecon.github.io/Math4Econ/), and for intro stat with R, see [Intro Statistics for Undergraduates](https://fanwangecon.github.io/Stat4Econ/). See [here](https://github.com/FanWangEcon) for all of [Fan](https://fanwangecon.github.io/)'s public repositories.

The site is built using [Bookdown](https://bookdown.org/) [@R-bookdown].

Please contact [FanWangEcon](https://fanwangecon.github.io/) for issues or problems.

`r text_end_count`
